# Generated by Django 6.1 on 2026-09-02 12:34

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Adresse e-mail')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('dateCreation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('statutCompte', models.BooleanField(default=True, verbose_name='Compte actif')),
                ('photoProfil', models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='Photo de profil')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Accès admin Django')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Super administrateur')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'inscription")),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('idPermission', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=150, unique=True, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('idPatient', models.AutoField(primary_key=True, serialize=False)),
                ('numeroPatient', models.CharField(max_length=50, unique=True, verbose_name='Numéro patient')),
                ('dateNaissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('sexe', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin'), ('A', 'Autre')], max_length=1, verbose_name='Sexe')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('niu', models.CharField(blank=True, max_length=20, verbose_name='NIU')),
                ('numeroCNI', models.CharField(blank=True, max_length=20, verbose_name='Numéro CNI')),
                ('nomContactUrgencePrincipal', models.CharField(max_length=200, verbose_name='Nom contact urgence')),
                ('telephoneContactUrgencePrincipal', models.CharField(max_length=20, verbose_name='Téléphone contact urgence')),
                ('lienContactUrgencePrincipal', models.CharField(max_length=50, verbose_name='Lien de parenté')),
                ('nomContactUrgenceSecondaire', models.CharField(blank=True, max_length=200, verbose_name='Nom contact urgence secondaire')),
                ('telephoneContactUrgenceSecondaire', models.CharField(blank=True, max_length=20, verbose_name='Téléphone contact urgence secondaire')),
                ('lienContactUrgenceSecondaire', models.CharField(blank=True, max_length=50, verbose_name='Lien de parenté secondaire')),
                ('utilisateur_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='patient_child', to='users.utilisateur')),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
            },
            bases=('users.utilisateur',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('idRole', models.AutoField(primary_key=True, serialize=False)),
                ('nomRole', models.CharField(max_length=50, unique=True, verbose_name='Nom du rôle')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='users.permission', verbose_name='Permissions')),
            ],
            options={
                'verbose_name': 'Rôle',
                'verbose_name_plural': 'Rôles',
            },
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('idPersonnel', models.AutoField(primary_key=True, serialize=False)),
                ('matricule', models.CharField(max_length=50, unique=True, verbose_name='Matricule')),
                ('dateAffectation', models.DateField(blank=True, null=True, verbose_name="Date d'affectation")),
                ('statutProfessionnel', models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif'), ('CONGE', 'En congé'), ('SUSPENDU', 'Suspendu')], default='ACTIF', max_length=20, verbose_name='Statut professionnel')),
                ('utilisateur_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='personnel_child', to='users.utilisateur')),
                ('roles', models.ManyToManyField(blank=True, related_name='personnel', to='users.role', verbose_name='Rôles')),
            ],
            options={
                'verbose_name': 'Personnel',
                'verbose_name_plural': 'Personnel',
            },
            bases=('users.utilisateur',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
