# Generated by Django 6.1 on 2026-09-02 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='patient',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='personnel',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='utilisateur',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='personnel',
            name='doitChangerMotDePasse',
            field=models.BooleanField(default=False, verbose_name='Doit changer son mot de passe'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='etablissement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnel', to='establishments.etablissement', verbose_name='Établissement'),
        ),
    ]
