# Generated by Django 6.1 on 2026-09-02 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_patient_managers_alter_personnel_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='roles',
        ),
        migrations.AddField(
            model_name='personnel',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnel', to='users.role', verbose_name='Rôle'),
        ),
    ]
