# Generated by Django 6.1 on 2026-09-02 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_personnel_roles_personnel_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='jeton_acces',
            field=models.CharField(blank=True, editable=False, max_length=64, verbose_name="Jeton d'accès personnel"),
        ),
    ]
