# Generated by Django 6.1 on 2026-09-03 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_utilisateur_jeton_acces'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='allergies',
            field=models.TextField(blank=True, default='', verbose_name='Allergies (séparées par virgule)'),
        ),
        migrations.AddField(
            model_name='patient',
            name='antecedents',
            field=models.TextField(blank=True, default='', verbose_name='Antécédents / Pathologies chroniques'),
        ),
        migrations.AddField(
            model_name='patient',
            name='groupeSanguin',
            field=models.CharField(blank=True, choices=[('', '— Non renseigné'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='', max_length=3, verbose_name='Groupe sanguin'),
        ),
        migrations.AddField(
            model_name='patient',
            name='traitementEnCours',
            field=models.TextField(blank=True, default='', verbose_name='Traitement en cours'),
        ),
    ]
