# Generated by Django 6.1 on 2026-09-07 00:31

from django.db import migrations, models


def retrocompleter_code_patient(apps, schema_editor):
    """Assigne un code de confirmation par défaut aux patients existants
    (démo), faute de quoi tout acte sur leur dossier identifié serait bloqué
    par la vérification du code sans aucun moyen de l'obtenir."""
    Patient = apps.get_model('users', 'Patient')
    Patient.objects.filter(codeConfirmation='').update(codeConfirmation='123456')


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_patient_allergies_patient_antecedents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='codeConfirmation',
            field=models.CharField(blank=True, default='', max_length=6, verbose_name='Code de confirmation patient'),
        ),
        migrations.AddField(
            model_name='patient',
            name='doitChangerMotDePasse',
            field=models.BooleanField(default=True, verbose_name='Doit changer son mot de passe à la première connexion'),
        ),
        migrations.RunPython(retrocompleter_code_patient, migrations.RunPython.noop),
    ]
