# Generated by Django 6.1 on 2026-09-07 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_patient_codeconfirmation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='nbEchecsConnexion',
            field=models.PositiveIntegerField(default=0, verbose_name='Échecs de connexion consécutifs'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='verrouillageJusqua',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Compte verrouillé jusqu'à"),
        ),
    ]
