# Generated by Django 6.1 on 2026-09-08 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_creer_superadmin_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='session_active_key',
            field=models.CharField(blank=True, default='', editable=False, max_length=64, verbose_name='Session active'),
        ),
    ]
