# Generated by Django 6.1 on 2026-09-24 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0004_etablissement_motifsuspension'),
        ('users', '0009_utilisateur_session_active_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='etablissement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='establishments.etablissement', verbose_name="Établissement d'affiliation"),
        ),
    ]
