# Generated by Django 6.1 on 2026-09-26 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_patient_etablissement'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientEncodage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moteur', models.CharField(default='onnx', max_length=8, verbose_name="Moteur d'encodage")),
                ('dimension', models.PositiveIntegerField(default=512, verbose_name='Dimension')),
                ('vecteur', models.JSONField(verbose_name='Vecteur facial (list de float)')),
                ('nb_visages', models.PositiveIntegerField(default=0, verbose_name='Visages détectés')),
                ('misAJourLe', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='encodage', to='users.patient', verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'Empreinte faciale patient',
                'verbose_name_plural': 'Empreintes faciales patients',
            },
        ),
    ]
