@startuml communication_urgence
' Diagramme de communication — Traitement d'une urgence
actor "Infirmier" as I
participant "Interface" as UI
participant "1: créer DUT" as DUT
participant "2: triage" as TRI
participant "3: constantes" as CT
participant "4: recherche faciale" as SRV
participant "5: confirmer identité" as RI
participant "6: fusionner DUT→DMP" as DMP

I --> UI
UI --> DUT : 1: créer(nouveau)
DUT --> UI : numeroDUT, statut ACTIF
UI --> TRI : 2: créer(priorité)
TRI --> DUT : 2.1: associer à DUT
UI --> CT : 3: créer(mesures)
UI --> SRV : 4: rechercher_correspondance(photo)
SRV --> UI : 4.1: patients + confiance
UI --> RI : 5: confirmer(patient)
RI --> UI : 5.1: identité confirmée
UI --> DMP : 6: fusionner_avec_dmp(dmp)
DMP --> UI : 6.1: DUT FUSIONNE + DMP rattaché

@enduml