# Generated by Django 6.1 on 2026-09-02 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dmp', '0001_initial'),
        ('establishments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constante',
            fields=[
                ('idConstante', models.AutoField(primary_key=True, serialize=False)),
                ('frequenceCardiaque', models.IntegerField(blank=True, null=True, verbose_name='Fréquence cardiaque (bpm)')),
                ('tensionArterielle', models.CharField(blank=True, max_length=20, verbose_name='Tension artérielle')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Température (°C)')),
                ('saturationOxygene', models.IntegerField(blank=True, null=True, verbose_name='Saturation O₂ (%)')),
                ('frequenceRespiratoire', models.IntegerField(blank=True, null=True, verbose_name='Fréquence respiratoire')),
                ('poids', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Poids (kg)')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date de mesure')),
            ],
            options={
                'verbose_name': 'Constante',
                'verbose_name_plural': 'Constantes',
            },
        ),
        migrations.CreateModel(
            name='JournalAudit',
            fields=[
                ('idJournal', models.AutoField(primary_key=True, serialize=False)),
                ('dateHeure', models.DateTimeField(auto_now_add=True, verbose_name='Date et heure')),
                ('action', models.CharField(max_length=255, verbose_name='Action')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('adresseIP', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
            ],
            options={
                'verbose_name': "Journal d'audit",
                'verbose_name_plural': "Journaux d'audit",
                'ordering': ['-dateHeure'],
            },
        ),
        migrations.CreateModel(
            name='RechercheIdentite',
            fields=[
                ('idRecherche', models.AutoField(primary_key=True, serialize=False)),
                ('statut', models.CharField(choices=[('EN_RECHERCHE', 'En recherche'), ('CORRESPONDANCE_TROUVEE', 'Correspondance trouvée'), ('CONFIRMEE', 'Confirmée'), ('AUCUNE', 'Aucune correspondance')], default='EN_RECHERCHE', max_length=30, verbose_name='Statut')),
                ('confiance', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Score de confiance (%)')),
                ('dateRecherche', models.DateTimeField(auto_now_add=True, verbose_name='Date de recherche')),
                ('dateConfirmation', models.DateTimeField(blank=True, null=True, verbose_name='Date de confirmation')),
            ],
            options={
                'verbose_name': "Recherche d'identité",
                'verbose_name_plural': "Recherches d'identité",
            },
        ),
        migrations.CreateModel(
            name='ServiceReconnaissanceFaciale',
            fields=[
                ('idService', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du service')),
                ('urlEndpoint', models.URLField(blank=True, verbose_name="URL de l'API")),
            ],
            options={
                'verbose_name': 'Service de reconnaissance faciale',
                'verbose_name_plural': 'Services de reconnaissance faciale',
            },
        ),
        migrations.CreateModel(
            name='Triage',
            fields=[
                ('idTriage', models.AutoField(primary_key=True, serialize=False)),
                ('priorite', models.CharField(choices=[('ROUGE', 'Réanimation'), ('ORANGE', 'Très urgent'), ('JAUNE', 'Urgent'), ('VERT', 'Peu urgent'), ('BLEU', 'Non urgent')], max_length=20, verbose_name='Priorité')),
                ('motifArrivee', models.CharField(max_length=255, verbose_name="Motif d'arrivée")),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('dateHeure', models.DateTimeField(auto_now_add=True, verbose_name='Date et heure')),
            ],
            options={
                'verbose_name': 'Triage',
                'verbose_name_plural': 'Triages',
            },
        ),
        migrations.CreateModel(
            name='DossierUrgenceTemporaire',
            fields=[
                ('idDUT', models.AutoField(primary_key=True, serialize=False)),
                ('numeroDUT', models.CharField(max_length=50, unique=True, verbose_name='Numéro DUT')),
                ('informationsInitiales', models.TextField(blank=True, verbose_name='Informations initiales')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='dut/photos/', verbose_name='Photo du patient')),
                ('dateCreation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('dateCloture', models.DateTimeField(blank=True, null=True, verbose_name='Date de clôture')),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('FUSIONNE', 'Fusionné'), ('INACTIF', 'Inactif')], default='ACTIF', max_length=20, verbose_name='Statut')),
                ('identiteConfirmee', models.BooleanField(default=False, verbose_name='Identité confirmée')),
                ('dateFusion', models.DateTimeField(blank=True, null=True, verbose_name='Date de fusion')),
                ('dmpRattache', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dmp.dossiermedicalpartage', verbose_name='DMP rattaché')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='duts', to='establishments.etablissement', verbose_name='Établissement')),
            ],
            options={
                'verbose_name': "Dossier d'Urgence Temporaire",
                'verbose_name_plural': "Dossiers d'Urgence Temporaires",
            },
        ),
    ]
