# Generated by Django 6.1 on 2026-09-02 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('urgences', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dossierurgencetemporaire',
            name='infirmier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='duts_crees', to=settings.AUTH_USER_MODEL, verbose_name='Infirmier'),
        ),
        migrations.AddField(
            model_name='constante',
            name='dut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constantes', to='urgences.dossierurgencetemporaire', verbose_name='DUT'),
        ),
        migrations.AddField(
            model_name='journalaudit',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.utilisateur', verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='rechercheidentite',
            name='confirmePar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmations_identite', to=settings.AUTH_USER_MODEL, verbose_name='Confirmé par'),
        ),
        migrations.AddField(
            model_name='rechercheidentite',
            name='dut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recherches_identite', to='urgences.dossierurgencetemporaire', verbose_name='DUT'),
        ),
        migrations.AddField(
            model_name='rechercheidentite',
            name='patientCorrespondant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.patient', verbose_name='Patient correspondant'),
        ),
        migrations.AddField(
            model_name='rechercheidentite',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='urgences.servicereconnaissancefaciale', verbose_name='Service utilisé'),
        ),
        migrations.AddField(
            model_name='triage',
            name='dut',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='triage', to='urgences.dossierurgencetemporaire', verbose_name='DUT'),
        ),
    ]
