# Generated by Django 6.1 on 2026-09-02 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0001_initial'),
        ('urgences', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='constante',
            name='etablissement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='constantes', to='establishments.etablissement', verbose_name='Établissement'),
        ),
        migrations.AddField(
            model_name='journalaudit',
            name='etablissement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='establishments.etablissement', verbose_name='Établissement'),
        ),
        migrations.AddField(
            model_name='rechercheidentite',
            name='etablissement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recherches_identite', to='establishments.etablissement', verbose_name='Établissement'),
        ),
        migrations.AddField(
            model_name='triage',
            name='etablissement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='triages', to='establishments.etablissement', verbose_name='Établissement'),
        ),
    ]
