# Generated by Django 6.1 on 2026-09-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urgences', '0003_constante_etablissement_journalaudit_etablissement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rechercheidentite',
            name='statut',
            field=models.CharField(choices=[('EN_RECHERCHE', 'En recherche'), ('CORRESPONDANCE_TROUVEE', 'Correspondance trouvée'), ('CONFIRMEE', 'Confirmée'), ('AUCUNE', 'Aucune correspondance'), ('REJETEE', 'Rejetée')], default='EN_RECHERCHE', max_length=30, verbose_name='Statut'),
        ),
    ]
