# Generated by Django 6.1 on 2026-09-08 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmp', '0005_accesdmp_dernierenvoinotification_and_more'),
        ('establishments', '0004_etablissement_motifsuspension'),
        ('urgences', '0004_alter_rechercheidentite_statut'),
        ('users', '0009_utilisateur_session_active_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='journalaudit',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journaux_patient', to='users.patient', verbose_name='Patient concerné'),
        ),
        migrations.AlterField(
            model_name='dossierurgencetemporaire',
            name='statut',
            field=models.CharField(choices=[('ACTIF', 'Actif'), ('EN_ATTENTE_PROLONGEE', 'En attente prolongée'), ('FUSIONNE', 'Fusionné'), ('INACTIF', 'Inactif')], default='ACTIF', max_length=20, verbose_name='Statut'),
        ),
        migrations.AddIndex(
            model_name='dossierurgencetemporaire',
            index=models.Index(fields=['dateCreation'], name='urgences_do_dateCre_fc50fd_idx'),
        ),
        migrations.AddIndex(
            model_name='dossierurgencetemporaire',
            index=models.Index(fields=['statut'], name='urgences_do_statut_4e70cb_idx'),
        ),
        migrations.AddIndex(
            model_name='journalaudit',
            index=models.Index(fields=['dateHeure'], name='urgences_jo_dateHeu_cc2ff4_idx'),
        ),
        migrations.AddIndex(
            model_name='journalaudit',
            index=models.Index(fields=['patient', 'dateHeure'], name='urgences_jo_patient_cb368b_idx'),
        ),
    ]
