# Generated by Django 6.1 on 2026-09-02 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('idEtablissement', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200, verbose_name="Nom de l'établissement")),
                ('adresse', models.CharField(max_length=255, verbose_name='Adresse')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email de contact')),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif'), ('SUSPENDU', 'Suspendu')], default='ACTIF', max_length=20, verbose_name='Statut')),
            ],
            options={
                'verbose_name': 'Établissement',
                'verbose_name_plural': 'Établissements',
            },
        ),
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('idCandidature', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('email', models.EmailField(max_length=254, verbose_name='Adresse e-mail')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('motivation', models.TextField(blank=True, verbose_name='Motivation')),
                ('roleDemande', models.CharField(max_length=50, verbose_name='Rôle demandé')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ACCEPTEE', 'Acceptée'), ('REFUSEE', 'Refusée')], default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('dateSoumission', models.DateTimeField(auto_now_add=True, verbose_name='Date de soumission')),
                ('dateDecision', models.DateTimeField(blank=True, null=True, verbose_name='Date de décision')),
                ('motifRefus', models.TextField(blank=True, verbose_name='Motif du refus')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='establishments.etablissement', verbose_name='Établissement')),
            ],
            options={
                'verbose_name': 'Candidature',
                'verbose_name_plural': 'Candidatures',
            },
        ),
    ]
