# Generated by Django 6.1 on 2026-09-02 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formule',
            fields=[
                ('idFormule', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la formule')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix (FCFA)')),
                ('dureeMois', models.PositiveIntegerField(verbose_name='Durée (mois)')),
                ('nbUtilisateursMax', models.PositiveIntegerField(verbose_name="Nombre max d'utilisateurs")),
                ('nbDMPMax', models.PositiveIntegerField(verbose_name='Nombre max de DMP')),
            ],
            options={
                'verbose_name': 'Formule',
                'verbose_name_plural': 'Formules',
            },
        ),
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('idAbonnement', models.AutoField(primary_key=True, serialize=False)),
                ('dateDebut', models.DateField(verbose_name='Date de début')),
                ('dateFin', models.DateField(verbose_name='Date de fin')),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('SUSPENDU', 'Suspendu'), ('EXPIRE', 'Expiré')], default='ACTIF', max_length=20, verbose_name='Statut')),
                ('datePaiement', models.DateTimeField(blank=True, null=True, verbose_name='Date du paiement')),
                ('etablissement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='abonnement', to='establishments.etablissement', verbose_name='Établissement')),
                ('formule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abonnements', to='establishments.formule', verbose_name='Formule')),
            ],
            options={
                'verbose_name': 'Abonnement',
                'verbose_name_plural': 'Abonnements',
            },
        ),
    ]
