# Generated by Django 6.1 on 2026-09-07 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0002_formule_abonnement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidature',
            name='motivation',
        ),
    ]
