# Generated by Django 6.1 on 2026-09-02 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dmp', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='medecin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultations', to=settings.AUTH_USER_MODEL, verbose_name='Médecin'),
        ),
        migrations.AddField(
            model_name='dossiermedicalpartage',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dmp', to='users.patient', verbose_name='Patient'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='dmp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='dmp.dossiermedicalpartage', verbose_name='DMP'),
        ),
        migrations.AddField(
            model_name='ligneprescription',
            name='medicament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_prescription', to='dmp.medicament', verbose_name='Médicament'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='consultation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='dmp.consultation', verbose_name='Consultation'),
        ),
        migrations.AddField(
            model_name='ligneprescription',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='dmp.prescription', verbose_name='Prescription'),
        ),
    ]
