# Generated by Django 6.1 on 2026-09-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmp', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='statut',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('ANNULEE', 'Annulée')], default='ACTIVE', max_length=20, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='statut',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('ANNULEE', 'Annulée')], default='ACTIVE', max_length=20, verbose_name='Statut'),
        ),
    ]
