# Generated by Django 6.1 on 2026-09-07 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmp', '0003_consultation_statut_prescription_statut'),
        ('establishments', '0004_etablissement_motifsuspension'),
        ('users', '0006_patient_codeconfirmation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccesDMP',
            fields=[
                ('idAcces', models.AutoField(primary_key=True, serialize=False)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ACCORDE', 'Accordé'), ('REFUSE', 'Refusé'), ('REVOQUE', 'Révoqué'), ('EXPIRE', 'Expiré')], default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('motif', models.CharField(blank=True, max_length=255, verbose_name='Motif')),
                ('dateDemande', models.DateTimeField(auto_now_add=True, verbose_name='Date de demande')),
                ('dateDecision', models.DateTimeField(blank=True, null=True, verbose_name='Date de décision')),
                ('demandeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='demandes_dmp', to=settings.AUTH_USER_MODEL, verbose_name='Demandeur')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acces_dmp', to='establishments.etablissement', verbose_name='Établissement')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acces_dmp', to='users.patient', verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'Accès DMP',
                'verbose_name_plural': 'Accès DMP',
                'ordering': ['-dateDemande'],
            },
        ),
    ]
