# Generated by Django 6.1 on 2026-09-08 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmp', '0004_accesdmp'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesdmp',
            name='dernierEnvoiNotification',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dernière notification envoyée'),
        ),
        migrations.AddField(
            model_name='accesdmp',
            name='nbNotificationsEnvoyees',
            field=models.PositiveIntegerField(default=0, verbose_name='Notifications e-mail envoyées'),
        ),
    ]
